name: lyssn_project
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  go_router: ^14.2.7
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  firebase_core: ^3.7.0
  firebase_analytics: ^11.3.4
  firebase_auth: ^5.3.2
  firebase_crashlytics: ^4.1.4
  cloud_firestore: ^5.5.0
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
