// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxCuemJoA-_2lXKItfOS_tj0Kz4jjmp1Y',
    appId: '1:75033975156:web:9356576f009bc21d833421',
    messagingSenderId: '75033975156',
    projectId: 'ios-weather-clone',
    authDomain: 'ios-weather-clone.firebaseapp.com',
    storageBucket: 'ios-weather-clone.firebasestorage.app',
    measurementId: 'G-97276E7QFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEk3uSsnEafjfiSOS6fhqjzqSKwqdQZyA',
    appId: '1:75033975156:android:6b2e17dd858113a4833421',
    messagingSenderId: '75033975156',
    projectId: 'ios-weather-clone',
    storageBucket: 'ios-weather-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEl2r2nSwCcw1_4L73r7oSNVPkVVzVuog',
    appId: '1:75033975156:ios:0554e1264c406c71833421',
    messagingSenderId: '75033975156',
    projectId: 'ios-weather-clone',
    storageBucket: 'ios-weather-clone.firebasestorage.app',
    iosBundleId: 'com.example.lyssnProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEl2r2nSwCcw1_4L73r7oSNVPkVVzVuog',
    appId: '1:75033975156:ios:0554e1264c406c71833421',
    messagingSenderId: '75033975156',
    projectId: 'ios-weather-clone',
    storageBucket: 'ios-weather-clone.firebasestorage.app',
    iosBundleId: 'com.example.lyssnProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxCuemJoA-_2lXKItfOS_tj0Kz4jjmp1Y',
    appId: '1:75033975156:web:75a30a3a48922f42833421',
    messagingSenderId: '75033975156',
    projectId: 'ios-weather-clone',
    authDomain: 'ios-weather-clone.firebaseapp.com',
    storageBucket: 'ios-weather-clone.firebasestorage.app',
    measurementId: 'G-RW6TXFV8C3',
  );
}
